// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPBsT6y3fXEWj1v8pnk54gmhLrSKgVxA',
    appId: '1:14781472975:web:d4d54fc26143d2c86197ba',
    messagingSenderId: '14781472975',
    projectId: 'bikeservice-82201',
    authDomain: 'bikeservice-82201.firebaseapp.com',
    storageBucket: 'bikeservice-82201.appspot.com',
    measurementId: 'G-NHKD60RQ0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fFQyvLXzazc2lTFfZt4tu9pq7cQ1c0w',
    appId: '1:14781472975:android:fe3c2bffe6efc4de6197ba',
    messagingSenderId: '14781472975',
    projectId: 'bikeservice-82201',
    storageBucket: 'bikeservice-82201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51j3xPtKBo8U1bZrBXj23T0n-ZR7AfyQ',
    appId: '1:14781472975:ios:8627f03a123ce27d6197ba',
    messagingSenderId: '14781472975',
    projectId: 'bikeservice-82201',
    storageBucket: 'bikeservice-82201.appspot.com',
    iosBundleId: 'com.example.bikeserviceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB51j3xPtKBo8U1bZrBXj23T0n-ZR7AfyQ',
    appId: '1:14781472975:ios:8627f03a123ce27d6197ba',
    messagingSenderId: '14781472975',
    projectId: 'bikeservice-82201',
    storageBucket: 'bikeservice-82201.appspot.com',
    iosBundleId: 'com.example.bikeserviceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmPBsT6y3fXEWj1v8pnk54gmhLrSKgVxA',
    appId: '1:14781472975:web:eefa955aaf582ea56197ba',
    messagingSenderId: '14781472975',
    projectId: 'bikeservice-82201',
    authDomain: 'bikeservice-82201.firebaseapp.com',
    storageBucket: 'bikeservice-82201.appspot.com',
    measurementId: 'G-HZWK9N1KSW',
  );
}
